import { createActions } from 'redux-actions'

export default createActions(
  'FETCH_LIST_REQUEST',
  'FETCH_LIST_SUCCESS',
  'FETCH_LIST_FAILURE',
  'FETCH_CURRENT_REQUEST',
  'FETCH_CURRENT_SUCCESS',
  'FETCH_CURRENT_FAILURE',
  'CREATE_REQUEST',
  'CREATE_SUCCESS',
  'CREATE_FAILURE',
  'UPDATE_REQUEST',
  'UPDATE_SUCCESS',
  'UPDATE_FAILURE',
  'DELETE_REQUEST',
  'DELETE_SUCCESS',
  'DELETE_FAILURE',
  'DELETE_CANCEL',
  { prefix: 'LOCALIZATION' }
)
