// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CurrencyService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MockSite.Message {

  /// <summary>Holder for reflection information generated from CurrencyService.proto</summary>
  public static partial class CurrencyServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for CurrencyService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CurrencyServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVDdXJyZW5jeVNlcnZpY2UucHJvdG8SB0FjY291bnQaFUN1cnJlbmN5TWVz",
            "c2FnZS5wcm90bxoTQ29tbW9uTWVzc2FnZS5wcm90bzKqAgoPQ3VycmVuY3lT",
            "ZXJ2aWNlEjEKBk1vZGlmeRIRLkFjY291bnQuQ3VycmVuY3kaFC5Db21tb24u",
            "QmFzZVJlc3BvbnNlEjQKDkdldEN1cnJlbmN5QWxsEg0uQ29tbW9uLkVtcHR5",
            "GhMuQWNjb3VudC5DdXJyZW5jaWVzEjcKA0dldBIdLkFjY291bnQuUXVlcnlD",
            "dXJyZW5jeU1lc3NhZ2UaES5BY2NvdW50LkN1cnJlbmN5Ej0KBkRlbGV0ZRId",
            "LkFjY291bnQuUXVlcnlDdXJyZW5jeU1lc3NhZ2UaFC5Db21tb24uQmFzZVJl",
            "c3BvbnNlEjYKEEdldFR0bEN1cnJlbmNpZXMSDS5Db21tb24uRW1wdHkaEy5B",
            "Y2NvdW50LkN1cnJlbmNpZXNCE6oCEE1vY2tTaXRlLk1lc3NhZ2ViBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MockSite.Message.CurrencyMessageReflection.Descriptor, global::MockSite.Message.CommonMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
