// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CurrencyService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MockSite.Message {
  public static partial class CurrencyService
  {
    static readonly string __ServiceName = "Account.CurrencyService";

    static readonly grpc::Marshaller<global::MockSite.Message.Currency> __Marshaller_Account_Currency = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MockSite.Message.Currency.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MockSite.Message.BaseResponse> __Marshaller_Common_BaseResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MockSite.Message.BaseResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MockSite.Message.Empty> __Marshaller_Common_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MockSite.Message.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MockSite.Message.Currencies> __Marshaller_Account_Currencies = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MockSite.Message.Currencies.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MockSite.Message.QueryCurrencyMessage> __Marshaller_Account_QueryCurrencyMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MockSite.Message.QueryCurrencyMessage.Parser.ParseFrom);

    static readonly grpc::Method<global::MockSite.Message.Currency, global::MockSite.Message.BaseResponse> __Method_Modify = new grpc::Method<global::MockSite.Message.Currency, global::MockSite.Message.BaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Modify",
        __Marshaller_Account_Currency,
        __Marshaller_Common_BaseResponse);

    static readonly grpc::Method<global::MockSite.Message.Empty, global::MockSite.Message.Currencies> __Method_GetCurrencyAll = new grpc::Method<global::MockSite.Message.Empty, global::MockSite.Message.Currencies>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCurrencyAll",
        __Marshaller_Common_Empty,
        __Marshaller_Account_Currencies);

    static readonly grpc::Method<global::MockSite.Message.QueryCurrencyMessage, global::MockSite.Message.Currency> __Method_Get = new grpc::Method<global::MockSite.Message.QueryCurrencyMessage, global::MockSite.Message.Currency>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_Account_QueryCurrencyMessage,
        __Marshaller_Account_Currency);

    static readonly grpc::Method<global::MockSite.Message.QueryCurrencyMessage, global::MockSite.Message.BaseResponse> __Method_Delete = new grpc::Method<global::MockSite.Message.QueryCurrencyMessage, global::MockSite.Message.BaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Delete",
        __Marshaller_Account_QueryCurrencyMessage,
        __Marshaller_Common_BaseResponse);

    static readonly grpc::Method<global::MockSite.Message.Empty, global::MockSite.Message.Currencies> __Method_GetTtlCurrencies = new grpc::Method<global::MockSite.Message.Empty, global::MockSite.Message.Currencies>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTtlCurrencies",
        __Marshaller_Common_Empty,
        __Marshaller_Account_Currencies);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MockSite.Message.CurrencyServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CurrencyService</summary>
    [grpc::BindServiceMethod(typeof(CurrencyService), "BindService")]
    public abstract partial class CurrencyServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::MockSite.Message.BaseResponse> Modify(global::MockSite.Message.Currency request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MockSite.Message.Currencies> GetCurrencyAll(global::MockSite.Message.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MockSite.Message.Currency> Get(global::MockSite.Message.QueryCurrencyMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MockSite.Message.BaseResponse> Delete(global::MockSite.Message.QueryCurrencyMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MockSite.Message.Currencies> GetTtlCurrencies(global::MockSite.Message.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CurrencyService</summary>
    public partial class CurrencyServiceClient : grpc::ClientBase<CurrencyServiceClient>
    {
      /// <summary>Creates a new client for CurrencyService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CurrencyServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CurrencyService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CurrencyServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CurrencyServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CurrencyServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::MockSite.Message.BaseResponse Modify(global::MockSite.Message.Currency request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Modify(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MockSite.Message.BaseResponse Modify(global::MockSite.Message.Currency request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Modify, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.BaseResponse> ModifyAsync(global::MockSite.Message.Currency request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ModifyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.BaseResponse> ModifyAsync(global::MockSite.Message.Currency request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Modify, null, options, request);
      }
      public virtual global::MockSite.Message.Currencies GetCurrencyAll(global::MockSite.Message.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCurrencyAll(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MockSite.Message.Currencies GetCurrencyAll(global::MockSite.Message.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCurrencyAll, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.Currencies> GetCurrencyAllAsync(global::MockSite.Message.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCurrencyAllAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.Currencies> GetCurrencyAllAsync(global::MockSite.Message.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCurrencyAll, null, options, request);
      }
      public virtual global::MockSite.Message.Currency Get(global::MockSite.Message.QueryCurrencyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MockSite.Message.Currency Get(global::MockSite.Message.QueryCurrencyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Get, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.Currency> GetAsync(global::MockSite.Message.QueryCurrencyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.Currency> GetAsync(global::MockSite.Message.QueryCurrencyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Get, null, options, request);
      }
      public virtual global::MockSite.Message.BaseResponse Delete(global::MockSite.Message.QueryCurrencyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Delete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MockSite.Message.BaseResponse Delete(global::MockSite.Message.QueryCurrencyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Delete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.BaseResponse> DeleteAsync(global::MockSite.Message.QueryCurrencyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.BaseResponse> DeleteAsync(global::MockSite.Message.QueryCurrencyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Delete, null, options, request);
      }
      public virtual global::MockSite.Message.Currencies GetTtlCurrencies(global::MockSite.Message.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTtlCurrencies(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MockSite.Message.Currencies GetTtlCurrencies(global::MockSite.Message.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTtlCurrencies, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.Currencies> GetTtlCurrenciesAsync(global::MockSite.Message.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTtlCurrenciesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.Currencies> GetTtlCurrenciesAsync(global::MockSite.Message.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTtlCurrencies, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CurrencyServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CurrencyServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CurrencyServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Modify, serviceImpl.Modify)
          .AddMethod(__Method_GetCurrencyAll, serviceImpl.GetCurrencyAll)
          .AddMethod(__Method_Get, serviceImpl.Get)
          .AddMethod(__Method_Delete, serviceImpl.Delete)
          .AddMethod(__Method_GetTtlCurrencies, serviceImpl.GetTtlCurrencies).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CurrencyServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Modify, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MockSite.Message.Currency, global::MockSite.Message.BaseResponse>(serviceImpl.Modify));
      serviceBinder.AddMethod(__Method_GetCurrencyAll, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MockSite.Message.Empty, global::MockSite.Message.Currencies>(serviceImpl.GetCurrencyAll));
      serviceBinder.AddMethod(__Method_Get, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MockSite.Message.QueryCurrencyMessage, global::MockSite.Message.Currency>(serviceImpl.Get));
      serviceBinder.AddMethod(__Method_Delete, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MockSite.Message.QueryCurrencyMessage, global::MockSite.Message.BaseResponse>(serviceImpl.Delete));
      serviceBinder.AddMethod(__Method_GetTtlCurrencies, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MockSite.Message.Empty, global::MockSite.Message.Currencies>(serviceImpl.GetTtlCurrencies));
    }

  }
}
#endregion
