// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LocalizationService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MockSite.Message {

  /// <summary>Holder for reflection information generated from LocalizationService.proto</summary>
  public static partial class LocalizationServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for LocalizationService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LocalizationServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlMb2NhbGl6YXRpb25TZXJ2aWNlLnByb3RvEgdBY2NvdW50GhlMb2NhbGl6",
            "YXRpb25NZXNzYWdlLnByb3RvGhNDb21tb25NZXNzYWdlLnByb3RvMvABChNM",
            "b2NhbGl6YXRpb25TZXJ2aWNlEjEKBk1vZGlmeRIRLkFjY291bnQuTGFuZ3Vh",
            "Z2UaFC5Db21tb24uQmFzZVJlc3BvbnNlEisKBkdldEFsbBINLkNvbW1vbi5F",
            "bXB0eRoSLkFjY291bnQuTGFuZ3VhZ2VzEjoKA0dldBIdLkFjY291bnQuUXVl",
            "cnlMYW5ndWFnZU1lc3NhZ2UaFC5BY2NvdW50Lkxhbmd1YWdlU2V0Ej0KBkRl",
            "bGV0ZRIdLkFjY291bnQuUXVlcnlMYW5ndWFnZU1lc3NhZ2UaFC5Db21tb24u",
            "QmFzZVJlc3BvbnNlQhOqAhBNb2NrU2l0ZS5NZXNzYWdlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MockSite.Message.LocalizationMessageReflection.Descriptor, global::MockSite.Message.CommonMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
