// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UserService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MockSite.Message {
  public static partial class UserService
  {
    static readonly string __ServiceName = "User.UserService";

    static readonly grpc::Marshaller<global::MockSite.Message.User> __Marshaller_User_User = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MockSite.Message.User.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MockSite.Message.ResponseBase> __Marshaller_User_ResponseBase = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MockSite.Message.ResponseBase.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MockSite.Message.Empty> __Marshaller_User_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MockSite.Message.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MockSite.Message.Users> __Marshaller_User_Users = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MockSite.Message.Users.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MockSite.Message.UserCode> __Marshaller_User_UserCode = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MockSite.Message.UserCode.Parser.ParseFrom);

    static readonly grpc::Method<global::MockSite.Message.User, global::MockSite.Message.ResponseBase> __Method_Create = new grpc::Method<global::MockSite.Message.User, global::MockSite.Message.ResponseBase>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Create",
        __Marshaller_User_User,
        __Marshaller_User_ResponseBase);

    static readonly grpc::Method<global::MockSite.Message.Empty, global::MockSite.Message.Users> __Method_GetAll = new grpc::Method<global::MockSite.Message.Empty, global::MockSite.Message.Users>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAll",
        __Marshaller_User_Empty,
        __Marshaller_User_Users);

    static readonly grpc::Method<global::MockSite.Message.UserCode, global::MockSite.Message.User> __Method_Get = new grpc::Method<global::MockSite.Message.UserCode, global::MockSite.Message.User>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_User_UserCode,
        __Marshaller_User_User);

    static readonly grpc::Method<global::MockSite.Message.User, global::MockSite.Message.ResponseBase> __Method_Update = new grpc::Method<global::MockSite.Message.User, global::MockSite.Message.ResponseBase>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Update",
        __Marshaller_User_User,
        __Marshaller_User_ResponseBase);

    static readonly grpc::Method<global::MockSite.Message.UserCode, global::MockSite.Message.ResponseBase> __Method_Delete = new grpc::Method<global::MockSite.Message.UserCode, global::MockSite.Message.ResponseBase>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Delete",
        __Marshaller_User_UserCode,
        __Marshaller_User_ResponseBase);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MockSite.Message.UserServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UserService</summary>
    public abstract partial class UserServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::MockSite.Message.ResponseBase> Create(global::MockSite.Message.User request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MockSite.Message.Users> GetAll(global::MockSite.Message.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MockSite.Message.User> Get(global::MockSite.Message.UserCode request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MockSite.Message.ResponseBase> Update(global::MockSite.Message.User request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MockSite.Message.ResponseBase> Delete(global::MockSite.Message.UserCode request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UserService</summary>
    public partial class UserServiceClient : grpc::ClientBase<UserServiceClient>
    {
      /// <summary>Creates a new client for UserService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UserServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UserService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UserServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UserServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UserServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::MockSite.Message.ResponseBase Create(global::MockSite.Message.User request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Create(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MockSite.Message.ResponseBase Create(global::MockSite.Message.User request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Create, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.ResponseBase> CreateAsync(global::MockSite.Message.User request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.ResponseBase> CreateAsync(global::MockSite.Message.User request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Create, null, options, request);
      }
      public virtual global::MockSite.Message.Users GetAll(global::MockSite.Message.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAll(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MockSite.Message.Users GetAll(global::MockSite.Message.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAll, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.Users> GetAllAsync(global::MockSite.Message.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.Users> GetAllAsync(global::MockSite.Message.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAll, null, options, request);
      }
      public virtual global::MockSite.Message.User Get(global::MockSite.Message.UserCode request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MockSite.Message.User Get(global::MockSite.Message.UserCode request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Get, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.User> GetAsync(global::MockSite.Message.UserCode request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.User> GetAsync(global::MockSite.Message.UserCode request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Get, null, options, request);
      }
      public virtual global::MockSite.Message.ResponseBase Update(global::MockSite.Message.User request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Update(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MockSite.Message.ResponseBase Update(global::MockSite.Message.User request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Update, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.ResponseBase> UpdateAsync(global::MockSite.Message.User request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.ResponseBase> UpdateAsync(global::MockSite.Message.User request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Update, null, options, request);
      }
      public virtual global::MockSite.Message.ResponseBase Delete(global::MockSite.Message.UserCode request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Delete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MockSite.Message.ResponseBase Delete(global::MockSite.Message.UserCode request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Delete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.ResponseBase> DeleteAsync(global::MockSite.Message.UserCode request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MockSite.Message.ResponseBase> DeleteAsync(global::MockSite.Message.UserCode request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Delete, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UserServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UserServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UserServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Create, serviceImpl.Create)
          .AddMethod(__Method_GetAll, serviceImpl.GetAll)
          .AddMethod(__Method_Get, serviceImpl.Get)
          .AddMethod(__Method_Update, serviceImpl.Update)
          .AddMethod(__Method_Delete, serviceImpl.Delete).Build();
    }

  }
}
#endregion
