// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UserService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MockSite.Message {

  /// <summary>Holder for reflection information generated from UserService.proto</summary>
  public static partial class UserServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for UserService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFVc2VyU2VydmljZS5wcm90bxIEVXNlchoRVXNlck1lc3NhZ2UucHJvdG8y",
            "1gEKC1VzZXJTZXJ2aWNlEigKBkNyZWF0ZRIKLlVzZXIuVXNlchoSLlVzZXIu",
            "UmVzcG9uc2VCYXNlEiIKBkdldEFsbBILLlVzZXIuRW1wdHkaCy5Vc2VyLlVz",
            "ZXJzEiEKA0dldBIOLlVzZXIuVXNlckNvZGUaCi5Vc2VyLlVzZXISKAoGVXBk",
            "YXRlEgouVXNlci5Vc2VyGhIuVXNlci5SZXNwb25zZUJhc2USLAoGRGVsZXRl",
            "Eg4uVXNlci5Vc2VyQ29kZRoSLlVzZXIuUmVzcG9uc2VCYXNlQhOqAhBNb2Nr",
            "U2l0ZS5NZXNzYWdlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MockSite.Message.UserMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
