// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UserService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MockSite.Message {

  /// <summary>Holder for reflection information generated from UserService.proto</summary>
  public static partial class UserServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for UserService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFVc2VyU2VydmljZS5wcm90bxIHQWNjb3VudBoRVXNlck1lc3NhZ2UucHJv",
            "dG8yngIKC1VzZXJTZXJ2aWNlEjsKBkNyZWF0ZRIaLkFjY291bnQuQ3JlYXRl",
            "VXNlck1lc3NhZ2UaFS5BY2NvdW50LkJhc2VSZXNwb25zZRIoCgZHZXRBbGwS",
            "Di5BY2NvdW50LkVtcHR5Gg4uQWNjb3VudC5Vc2VycxIvCgNHZXQSGS5BY2Nv",
            "dW50LlF1ZXJ5VXNlck1lc3NhZ2UaDS5BY2NvdW50LlVzZXISOwoGVXBkYXRl",
            "EhouQWNjb3VudC5VcGRhdGVVc2VyTWVzc2FnZRoVLkFjY291bnQuQmFzZVJl",
            "c3BvbnNlEjoKBkRlbGV0ZRIZLkFjY291bnQuUXVlcnlVc2VyTWVzc2FnZRoV",
            "LkFjY291bnQuQmFzZVJlc3BvbnNlQhOqAhBNb2NrU2l0ZS5NZXNzYWdlYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MockSite.Message.UserMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
