// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UserService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MockSite.Message {

  /// <summary>Holder for reflection information generated from UserService.proto</summary>
  public static partial class UserServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for UserService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFVc2VyU2VydmljZS5wcm90bxIHQWNjb3VudBoTQ29tbW9uTWVzc2FnZS5w",
            "cm90bxoRVXNlck1lc3NhZ2UucHJvdG8y/QIKC1VzZXJTZXJ2aWNlEjMKBkNy",
            "ZWF0ZRIaLkFjY291bnQuQ3JlYXRlVXNlck1lc3NhZ2UaDS5BY2NvdW50LlVz",
            "ZXISPAoGR2V0QWxsEhouQWNjb3VudC5RdWVyeVVzZXJzTWVzc2FnZRoWLkFj",
            "Y291bnQuVXNlcnNSZXNwb25zZRJLCgxBdXRoZW50aWNhdGUSHC5BY2NvdW50",
            "LkF1dGhlbnRpY2F0ZU1lc3NhZ2UaHS5BY2NvdW50LkF1dGhlbnRpY2F0ZVJl",
            "c3BvbnNlEjcKA0dldBIZLkFjY291bnQuUXVlcnlVc2VyTWVzc2FnZRoVLkFj",
            "Y291bnQuVXNlclJlc3BvbnNlEjoKBlVwZGF0ZRIaLkFjY291bnQuVXBkYXRl",
            "VXNlck1lc3NhZ2UaFC5Db21tb24uQmFzZVJlc3BvbnNlEjkKBkRlbGV0ZRIZ",
            "LkFjY291bnQuUXVlcnlVc2VyTWVzc2FnZRoULkNvbW1vbi5CYXNlUmVzcG9u",
            "c2VCE6oCEE1vY2tTaXRlLk1lc3NhZ2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MockSite.Message.CommonMessageReflection.Descriptor, global::MockSite.Message.UserMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
