version: '3'

services:
  TestDB:
    image: mariadb:10.4.11
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass.123
    volumes:
      - "./dump:/docker-entrypoint-initdb.d"
      - "./my.cnf:/etc/mysql/my.cnf"
    stdin_open: true
    tty: true

  Jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  consul-sb-mocksite:
    container_name: consul-sb-mocksite
    image: consul:1.6.2
    ports:
      - "18500:8500"
    command: "agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0"

  mongoTest:
    image: mongo
    ports:
      - "27017:27017"

  TestRedis:
    image: redis
    ports:
     - "6379:6379"
